version: "3"
services:
    nginx:
        image: nginx:1.15-alpine
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/
        ports:
            - 8080:80
        depends_on:
            - php-fpm
            - postgres
    php:
        image: jguyomard/laravel-php:7.2
        volumes:
            - ./:/var/www/
            - $HOME/.composer/:$HOME/.composer/
        environment:
            - DB_HOST=${DB_HOST}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
    node:
        image: node:10.13-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true
    postgres:
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - postgres-data:/var/lib/postgresql/data
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
volumes:
    postgres-data:
